apiVersion: v1
kind: Service
metadata:
  name: block-diagram-postgres
  namespace: block-diagram
  labels:
    app: block-diagram-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: block-diagram-postgres
